### ISSUE TITLE
PowerShell language doesn't work

### ISSUE THREAD

**Issue by TechDufus** [shoukoo/commentary.nvim#1]
When I try to add my own languages (to test before PRing them), PowerShell is not working for me...

Was hoping you could either help me test, or see what I'm doing wrong..

I'm adding the following config:
```lua
require("commentary").setup({languages=
  {
    powershell = {single_line_comment =  "#", multiline_comment = {"#"}, prefer_multiline = false},
  }
})
```
But PowerShell files still use the default `//` for comments.

When in a `.ps1` PowerShell file and run `:set filetype?` I get `ps1` back as the type. So I've also tried the following config:
```lua
require("commentary").setup({languages=
  {
    ps1 = {single_line_comment =  "#", multiline_comment = {"#"}, prefer_multiline = false},
  }
})
```
 
Can you assist? This plugin is a lifesaver, and I'd love to help add languages!

**Comment by shoukoo** [comment]
Hey, thanks for reporting this bug. I have addressed it in this PR https://github.com/shoukoo/commentary.nvim/pull/2

**Comment by TechDufus** [comment]
So question... There wasn't anything wrong with how I was adding languages?

**Comment by shoukoo** [comment]
The bug was at my end where the code was running the `setup` function twice which overrides the custom language. 

This issue should be fixed If you updated to the latest version.

**Comment by shoukoo** [comment]
The bug was at my end where the code was running the `setup` function twice which overrides the custom language. 

This issue should be fixed If you updated to the latest version.
